<%@ Page Title="" Language="C#" MasterPageFile="~/IU/appGesion.Master" AutoEventWireup="true" CodeBehind="Index.aspx.cs" Inherits="appGestion.IU.WebForm1" %>
<asp:Content ID="indexContenido" ContentPlaceHolderID="contenido" runat="server">
    
    <asp:Label ID="prueba" runat="server" Text="Label"></asp:Label>

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:proyectoConnection %>" 
        ProviderName="<%$ ConnectionStrings:proyectoConnection.ProviderName %>" 
        DataSourceMode="DataSet"
        UpdateCommand="UPDATE empresas SET nombre=?, ciudad=?, nEmp=?, tipo=? WHERE cif=?;">
        
        <UpdateParameters>
            <asp:Parameter Name="nombre" Type="String"/>
            <asp:Parameter Name="ciudad" Type="String"/>
            <asp:Parameter Name="nEmp" Type="String"/>
            <asp:Parameter Name="tipo" Type="String" />
        </UpdateParameters>
 
    </asp:SqlDataSource>

    <asp:GridView ID="GridView1" runat="server" 
        AllowPaging="True" 
        AllowSorting="True" 
        AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" 
        DataKeyNames="cif" 
        DataSourceID="SqlDataSource1" 
        PageSize="3" 
        CssClass="grid_9">
        <Columns>
            <asp:BoundField DataField="cif" HeaderText="cif" ReadOnly="True" 
                SortExpression="cif" />
            <asp:BoundField DataField="nombre" HeaderText="nombre" 
                SortExpression="nombre" />
            <asp:BoundField DataField="ciudad" HeaderText="ciudad" 
                SortExpression="ciudad" />
            <asp:BoundField DataField="nEmp" HeaderText="nEmp" SortExpression="nEmp" />
            
            
            <asp:TemplateField HeaderText="Tipo">
                <ItemTemplate>
                    <asp:Label runat="server" text='<%# Eval("Tipo") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:DropDownList ID="tipo" runat="server" AutoPostBack="True">
                        <asp:ListItem Text="Potenciales" Value="p"></asp:ListItem>
                        <asp:ListItem Text="Firmes" Value="f"></asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
            </asp:TemplateField>
            
        </Columns>
        <PagerSettings PageButtonCount="3" />
    </asp:GridView>

    </asp:Content>
